apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end2-00001-deployment
  namespace: ahmedcano-dev
  labels:
    app: back-end2
    app.kubernetes.io/component: back-end2
    app.kubernetes.io/instance: back-end2
    app.kubernetes.io/part-of: phase-3-git-app
  annotations:
    autoscaling.knative.dev/target: "100"
    autoscaling.knative.dev/target-utilization-percentage: "70"
    autoscaling.knative.dev/window: "60s"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end2
  template:
    metadata:
      labels:
        app: back-end2
        app.kubernetes.io/component: back-end2
    spec:
  containers:
    - name: back-end2
      imagePullPolicy: Always
      image: image-registry.openshift-image-registry.svc:5000/ahmedcano-dev/back-end2:latest
      ports:
        - containerPort: 8001
          name: http
      env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
        - name: PORT
          value: "8001"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      readinessProbe:
        httpGet:
          path: /
          port: 8001
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
    - name: queue-proxy
      image: registry.redhat.io/openshift-serverless-1/serving-queue-rhel8:latest
      ports:
        - containerPort: 8012
          name: queue-port
      env:
        - name: USER_PORT
          value: "8001"
        - name: SERVING_NAMESPACE
          value: ahmedcano-dev
        - name: SERVING_SERVICE
          value: back-end2
        - name: SERVING_CONFIGURATION
          value: back-end2
        - name: SERVING_REVISION
          value: back-end2-00001
        - name: QUEUE_SERVING_PORT
          value: "8012"
        - name: ENABLE_HTTP_FULL_DUPLEX
          value: "false"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      readinessProbe:
        httpGet:
          path: /
          port: 8012
        initialDelaySeconds: 3
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
